# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pines.xdc

# Block Designs: bd/ROM/ROM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM} -quiet] -quiet

# IP: bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/clk/clk.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk || ORIG_REF_NAME==clk} -quiet] -quiet

# IP: bd/clk/ip/clk_processing_system7_0_0/clk_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_processing_system7_0_0 || ORIG_REF_NAME==clk_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Users/matia/Desktop/prueba/Generador_Zybo/Generador_Zybo.gen/sources_1/bd/ROM/ROM_ooc.xdc

# XDC: c:/Users/matia/Desktop/prueba/Generador_Zybo/Generador_Zybo.gen/sources_1/bd/clk/clk_ooc.xdc
